---
driver_plugin: vagrant
# driver_config:
#   require_chef_omnibus: latest
provisioner:
  name: chef_solo

platforms:
- name: centos-6.5-vmware
  driver_config:
    box: centos-6.5
    box_url: https://nmd-vmware.s3-us-west-2.amazonaws.com/nmd-centos-6.5-x86_64-base.box
    run_list:
- name: centos-6.5-virtualbox
  driver_config:
    box: centos-6.5
    box_url: https://nmd-virtualbox.s3-us-west-2.amazonaws.com/nmd-centos-6.5-x86_64-base.box
    run_list:
suites:
- name: default
  driver_config:
    box: centos-6.5
  run_list:
    - recipe[nmd_openldap::default]
    - recipe[nmd_openldap::makeselfsignedcert]
    - recipe[nmd_openldap::server]
    - recipe[nmd_openldap::client]
    - recipe[nmd_openldap::dit]
    - recipe[nmd_openldap::populate]
    - recipe[nmd_openldap::ppolicy]
  data_bags_path: "<%= ENV['DATA_BAGS_PATH'] %>"
  attributes:
